### ISSUE TITLE
Giving the wrong semester for the recent attendence

### ISSUE THREAD

**Issue by Akshaansh1** [codelif/pyjiit#4]
It is giving me the data for the 3rd sem and is showing me that my current semester is third which is wrong.

**Comment by codelif** [comment]
could you try again after updating pyjiit `pip install --upgrade pyjiit`

I merged a patch today at midnight, related to this.

**Comment by Akshaansh1** [comment]
Yes I saw the recent PR on the same issue. Thanks!

**Comment by codelif** [comment]
Thanks to @yryuvraj 

Closing this.
